# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029f2abf39ca7ab4c469fe3d9458fd8ef266d60be58422df32f5f841405b1e4a4ce30150b0b982ca36b9761a4c83828ec731db2a1595eb99be88b3c8d4dff1b1

test:
  secret_key_base: 4b6625c448e983aa4389d864b80fff625342abd3b15155a7a8ebc833059c2889d410d34424cbfac2ef89049dee17f2102ad72232a455c02d12cc8f391239809e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
